---
- hosts: all
  vars:
    current_user: "{{ ansible_user_id }}"
    new_shell: "{{ '/bin/zsh' }}"
    packages:
      - git
      - tmux
      - vim
      - zsh
    git_repos:
      - { repo: 'https://github.com/mrxcitement/dot-vim.git',
          dest: '~/github/mrxcitement/dot-vim',
          version: master }
      - { repo: 'https://github.com/mrxcitement/dot-zsh.git',
          dest: '~/github/mrxcitement/dot-zsh',
          version: master }

  tasks:
    - name: "Install software"
      become: true
      package:
        name: "{{ packages }}"
        state: present

    - name: "Clone dot-file repositories"
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items: "{{ git_repos }}"

    - name: "Install dot-file repositories"
      register: install
      command:
        chdir: "{{ item.dest }}"
        cmd: "./install"
      with_items: "{{ git_repos }}"
      changed_when: "'Link' in install.stdout"

    - name: "Change current user's shell to {{ new_shell }}"
      become: true
      user:
        name: "{{ current_user }}"
        shell: "{{ new_shell }}"
