---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: debian10-devbox
    box: generic/debian10
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
