# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "molecule"
  molecule:
  
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Check vagrant version and list plugins
        run: |
          vagrant --version
          vagrant plugin list
        shell: bash

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
    
      - name: Install pip requirements
        run: |
          pip install --no-input --no-cache-dir -r requirements.txt
        shell: bash

      - name: Run molecule test
        run: molecule test
        shell: bash
        env:
          ANSIBLE_FORCE_COLOR: true
          PY_COLORS: '1'
